/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as Upsell1RouteImport } from './routes/upsell1'
import { Route as Upsell2RouteImport } from './routes/upsell2'
import { Route as Upsell3RouteImport } from './routes/upsell3'
import { Route as Upsell4RouteImport } from './routes/upsell4'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiPublicEmailTestRouteImport } from './routes/api/public/email-test'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicAnalyticsUpsellRedirectRouteImport } from './routes/api/public/analytics/upsell-redirect'
import { Route as ApiPublicPixCreateRouteImport } from './routes/api/public/pix/create'
import { Route as ApiPublicPixStatusRouteImport } from './routes/api/public/pix/status'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix/webhook'
import { Route as ApiPublicSupportChatRouteImport } from './routes/api/public/support/chat'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell1',
  path: '/upsell1',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell2',
  path: '/upsell2',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell3Route = Upsell3RouteImport.update({
  id: '/upsell3',
  path: '/upsell3',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell4Route = Upsell4RouteImport.update({
  id: '/upsell4',
  path: '/upsell4',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailTestRoute = ApiPublicEmailTestRouteImport.update({
  id: '/api/public/email-test',
  path: '/api/public/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsUpsellRedirectRoute =
  ApiPublicAnalyticsUpsellRedirectRouteImport.update({
    id: '/api/public/analytics/upsell-redirect',
    path: '/api/public/analytics/upsell-redirect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPixCreateRoute = ApiPublicPixCreateRouteImport.update({
  id: '/api/public/pix/create',
  path: '/api/public/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixStatusRoute = ApiPublicPixStatusRouteImport.update({
  id: '/api/public/pix/status',
  path: '/api/public/pix/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix/webhook',
  path: '/api/public/pix/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportChatRoute = ApiPublicSupportChatRouteImport.update({
  id: '/api/public/support/chat',
  path: '/api/public/support/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/upsell4': typeof Upsell4Route
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/email-test': typeof ApiPublicEmailTestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/analytics/upsell-redirect': typeof ApiPublicAnalyticsUpsellRedirectRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/support/chat': typeof ApiPublicSupportChatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/upsell4': typeof Upsell4Route
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/email-test': typeof ApiPublicEmailTestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/analytics/upsell-redirect': typeof ApiPublicAnalyticsUpsellRedirectRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/support/chat': typeof ApiPublicSupportChatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/upsell1': typeof Upsell1Route
  '/upsell2': typeof Upsell2Route
  '/upsell3': typeof Upsell3Route
  '/upsell4': typeof Upsell4Route
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/email-test': typeof ApiPublicEmailTestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/analytics/upsell-redirect': typeof ApiPublicAnalyticsUpsellRedirectRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/support/chat': typeof ApiPublicSupportChatRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obrigado'
    | '/oferta'
    | '/pagamento'
    | '/unsubscribe'
    | '/upsell1'
    | '/upsell2'
    | '/upsell3'
    | '/upsell4'
    | '/email/unsubscribe'
    | '/api/public/email-test'
    | '/lovable/email/suppression'
    | '/api/public/analytics/upsell-redirect'
    | '/api/public/pix/create'
    | '/api/public/pix/status'
    | '/api/public/pix/webhook'
    | '/api/public/support/chat'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obrigado'
    | '/oferta'
    | '/pagamento'
    | '/unsubscribe'
    | '/upsell1'
    | '/upsell2'
    | '/upsell3'
    | '/upsell4'
    | '/email/unsubscribe'
    | '/api/public/email-test'
    | '/lovable/email/suppression'
    | '/api/public/analytics/upsell-redirect'
    | '/api/public/pix/create'
    | '/api/public/pix/status'
    | '/api/public/pix/webhook'
    | '/api/public/support/chat'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/obrigado'
    | '/oferta'
    | '/pagamento'
    | '/unsubscribe'
    | '/upsell1'
    | '/upsell2'
    | '/upsell3'
    | '/upsell4'
    | '/email/unsubscribe'
    | '/api/public/email-test'
    | '/lovable/email/suppression'
    | '/api/public/analytics/upsell-redirect'
    | '/api/public/pix/create'
    | '/api/public/pix/status'
    | '/api/public/pix/webhook'
    | '/api/public/support/chat'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObrigadoRoute: typeof ObrigadoRoute
  OfertaRoute: typeof OfertaRoute
  PagamentoRoute: typeof PagamentoRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Upsell1Route: typeof Upsell1Route
  Upsell2Route: typeof Upsell2Route
  Upsell3Route: typeof Upsell3Route
  Upsell4Route: typeof Upsell4Route
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicEmailTestRoute: typeof ApiPublicEmailTestRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicAnalyticsUpsellRedirectRoute: typeof ApiPublicAnalyticsUpsellRedirectRoute
  ApiPublicPixCreateRoute: typeof ApiPublicPixCreateRoute
  ApiPublicPixStatusRoute: typeof ApiPublicPixStatusRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
  ApiPublicSupportChatRoute: typeof ApiPublicSupportChatRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell1': {
      id: '/upsell1'
      path: '/upsell1'
      fullPath: '/upsell1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell2': {
      id: '/upsell2'
      path: '/upsell2'
      fullPath: '/upsell2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell3': {
      id: '/upsell3'
      path: '/upsell3'
      fullPath: '/upsell3'
      preLoaderRoute: typeof Upsell3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell4': {
      id: '/upsell4'
      path: '/upsell4'
      fullPath: '/upsell4'
      preLoaderRoute: typeof Upsell4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-test': {
      id: '/api/public/email-test'
      path: '/api/public/email-test'
      fullPath: '/api/public/email-test'
      preLoaderRoute: typeof ApiPublicEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics/upsell-redirect': {
      id: '/api/public/analytics/upsell-redirect'
      path: '/api/public/analytics/upsell-redirect'
      fullPath: '/api/public/analytics/upsell-redirect'
      preLoaderRoute: typeof ApiPublicAnalyticsUpsellRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/create': {
      id: '/api/public/pix/create'
      path: '/api/public/pix/create'
      fullPath: '/api/public/pix/create'
      preLoaderRoute: typeof ApiPublicPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/status': {
      id: '/api/public/pix/status'
      path: '/api/public/pix/status'
      fullPath: '/api/public/pix/status'
      preLoaderRoute: typeof ApiPublicPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/webhook': {
      id: '/api/public/pix/webhook'
      path: '/api/public/pix/webhook'
      fullPath: '/api/public/pix/webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support/chat': {
      id: '/api/public/support/chat'
      path: '/api/public/support/chat'
      fullPath: '/api/public/support/chat'
      preLoaderRoute: typeof ApiPublicSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObrigadoRoute: ObrigadoRoute,
  OfertaRoute: OfertaRoute,
  PagamentoRoute: PagamentoRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Upsell1Route: Upsell1Route,
  Upsell2Route: Upsell2Route,
  Upsell3Route: Upsell3Route,
  Upsell4Route: Upsell4Route,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicEmailTestRoute: ApiPublicEmailTestRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicAnalyticsUpsellRedirectRoute: ApiPublicAnalyticsUpsellRedirectRoute,
  ApiPublicPixCreateRoute: ApiPublicPixCreateRoute,
  ApiPublicPixStatusRoute: ApiPublicPixStatusRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
  ApiPublicSupportChatRoute: ApiPublicSupportChatRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
